[package]
name = "xmlem"
version = "0.0.0"
edition = "2021"
description = "mlem"
license = "Apache-2.0 OR MIT"

[dependencies]
indexmap = "1.8.1"
once_cell = "1.10.0"
quick-xml = "0.22.0"
slotmap = "1.0.6"
