[package]
name = "xmlem"
version = "0.0.0"
edition = "2021"
description = "mlem"
license = "Apache-2.0 OR MIT"

[dependencies]
cssparser = "0.28.1"
indexmap = "1.8.1"
once_cell = "1.10.0"
quick-xml = "0.22.0"
selectors = "0.23.0"
slotmap = "1.0.6"
unic-ucd = "0.9.0"
